### ISSUE TITLE
Django-modeltranslation and upy

### ISSUE THREAD

**Issue by Arussil** [20tab/upy#69]
Django-modeltranslation need the languages declared in settings.LANGUAGES, for that you need to set config.USE_UPY_G11N = False .

That means that config.USE_UPY_TREE also must be set to False.

Doing that will give this error while doing a syncdb:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 453, in execute_from_command_line
    utility.execute()
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/conf/**init**.py", line 53, in **getattr**
    self._setup(name)
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/home/arussil/Lavori/tour/project/project/settings.py", line 6, in <module>
    validate_config(project.config)
  File "/home/arussil/Lavori/venvs/tour_venv/local/lib/python2.7/site-packages/upy/upy_conf.py", line 47, in validate_config
    if config.USE_STATIC_PAGE:
AttributeError: 'module' object has no attribute 'USE_STATIC_PAGE'

**Comment by Arussil** [comment]
Guido explained how it works now, as i can't delete the issue i will leave it here for future reference.

**Comment by rafleze** [comment]
G11n doesn't exist yet. I fixed this problem.
